routes/web.php
    Route::patch('/banner/type/{banner}', 'BannerController@type')->name('banner.type');

    Route::get('/log-bank', 'LogMoneyController@log_bank')->name('log.bank');
    Route::get('/log-wallet', 'LogMoneyController@log_wallet')->name('log.wallet');
    Route::get('/log-transaction', 'LogMoneyController@log_transaction')->name('log.transaction');
    Route::get('/log-point', 'LogMoneyController@log_point')->name('log.point');
    Route::get('/log-order', 'LogMoneyController@log_order')->name('log.order');

    // Chức năng mua điểm
    Route::get('/point', 'UserController@buy_point')->name('point.index');
    Route::post('/point/update', 'UserController@update_point')->name('point.update');

    // Quản lý nạp / rút
    Route::get('recharge','PaymentController@recharge')->name('payment.recharge');
    Route::patch('post_recharge/{id}','PaymentController@post_recharge')->name('payment.post_recharge');


    Route::get('withdraw','PaymentController@withdraw')->name('payment.withdraw');
    Route::patch('withdraw/{id}','PaymentController@post_withdraw')->name('payment.post_withdraw');
    //End

    Route::get('search-affiliate', 'AffiliateController@searchAffiliate')->name('affiliate.searchAffiliate');
    // Xuất file Excel
    Route::get('export', 'OrderController@exportOrders')->name('exportOrders');
    Route::get('export', 'OrderController@export')->name('export');

    // Quản lý danh mục sản phẩm
    Route::resource('category', 'CategoryController');

    // Tính và cộng thưởng hoa hồng theo tháng
    Route::get('/bonus',  [OrdersController::class,'month_bonus'])->name('bonus');

    // Cấu hình % hoa hồng, thu nhập, thưởng
    Route::get('rose-config', 'ConfigController@rose_config')->name('rose.config');
    Route::post('rose-update', 'ConfigController@rose_update')->name('rose.update');
    // Cấu hình thưởng nhóm theo ngày
    Route::get('group-bonus', 'ConfigController@group_bonus_config')->name('group_bonus.config');
    Route::post('group-bonus-update', 'ConfigController@group_bonus_update')->name('group_bonus.update');
    // Cấu hình thưởng thu nhập/thu nhập
    Route::get('incomes', 'ConfigController@incomes_config')->name('incomes.config');
    Route::post('incomes-update', 'ConfigController@incomes_update')->name('incomes.update');

    // Hiển thị danh sách đội nhóm
    Route::get('groups', 'AffiliateController@show_groups')->name('group.index');
    Route::get('group_detail/{group_name}', 'AffiliateController@group_detail')->name('group.group_detail');

    // Săn Voucher
    Route::get('san-voucher', 'VoucherController@index')->name('voucher.index');
    Route::post('confirm-san-voucher/{id}', 'VoucherController@confirm')->name('voucher.confirm');
    Route::post('destroy-san-voucher/{id}', 'VoucherController@destroy')->name('voucher.destroy');


});

// Customer router (Đại lý)
Route::get('customers/login', [LoginsController::class,'index'])->name('us.login.index');
Route::post('customers/login', [LoginsController::class,'login'])->name('us.login');

Route::get('customers/group', [HomesController::class,'group_money']);

Route::group(['prefix' => '/customers', 'as' => 'us.', 'namespace' => 'Customer', 'middleware' => 'customerLogin'],function () {
    Route::get('san-pham-dau','ProductsController@checkmember')->name('checkmember');
    Route::post('san-pham','ProductsController@add_to_cart')->name('product.add_to_cart');
    Route::get('san-pham-checkout','ProductsController@checkout')->name('product.checkout');
    Route::get('san-pham-reset','ProductsController@reset')->name('product.reset');
    Route::post('san-pham-thanh-toan','ProductsController@store_dau_vao')->name('product.store_dau_vao');


    Route::get('mua-san-pham-dau/{id}','ProductsController@store')->name('buycombo.store');
    Route::get('thong-tin-san-pham-dau-tu','ProductsController@info')->name('buycombo.info');
    Route::get('thanh-toan-san-pham-dau-tu','ProductController@payment')->name('buycombo.payment');
//    Route::get('mua-san-pham-dau','ProductsController@store')->name('buycombo.store');
    Route::group(['middleware' => 'checkMember'], function (){
        Route::get('/', [HomesController::class,'index'])->name('home');
        Route::resource('account', 'AccountController')->only('index','update');

        Route::get('group_detail/{group_name}', 'IonGroupController@show')->name('group.show');

        // Chuyển ví
        Route::post('bank_account', 'AccountController@bank_account')->name('bank.bank_account');
        Route::get('bank_wallet', 'AccountController@bank_wallet_view')->name('bank.bank_wallet_view');
        Route::post('bank_wallet/{user}', 'AccountController@bank_wallet')->name('bank.bank_wallet');
        Route::get('chuyen-diem', 'AccountController@bank_out_view')->name('bank.bank_out_view');
        Route::post('chuyen-diem-post', 'AccountController@bank_transfer')->name('bank.bank_out');
        Route::get('bank/search', 'AccountController@search_receiver')->name('bank.search_receiver');

        // Nạp tiền
        Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('payment-history', 'PaymentController@history')->name('payment.history');
        Route::post('payment-offline', 'PaymentController@payment_offline')->name('payment.offline');
        //End
        //Rút tiền
        //Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('rut-diem', 'PaymentController@withdraw')->name('payment.withdraw');
        Route::post('payment-withdraw', 'PaymentController@post_withdraw')->name('payment.post_withdraw');
        Route::get('lich-su-rut-diem', 'PaymentController@history_withdraw')->name('payment.history_withdraw');
        // End

        // Lịch sử giao dịch
        Route::get('/history', 'AccountController@history')->name('history');

        Route::get('order', 'OrdersController@index')->name('order.index');
        Route::resource('affiliate', 'AffiliatesController')->only('index');
        Route::resource('customer', 'CustomersController')->only('index');
        Route::resource('product', 'ProductsController')->only('index');
        Route::resource('package', 'PackageController')->only('index');
        // Route::get('pay-product/{product}', 'PayController@index')->name('pay.product')->middleware(['checkOrder']);
        Route::resource('bank', 'BankAccountController')->only('index','store','update');
        Route::get('logout', 'LoginsController@logout')->name('logout');
        Route::post('search', 'BankAccountController@search')->name('search');

        Route::get('network/affiliate', 'AffiliatesController@index')->name('aff.index');

        // Cửa hàng
        Route::resource('product','ProductController')->except('show');
        Route::get('san-pham-dau-tu','ProductController@combo')->name('pro.combo');
        Route::get('san-pham-dau-tu/mua/{id}','ProductController@combo_store')->name('product.combo_store');

        // Săn Voucher
        Route::get('san-voucher','VoucherController@index')->name('voucher.index');
        Route::post('san-voucher','VoucherController@buy')->name('voucher.buy');
        Route::post('upload_bill','VoucherController@upload_bill')->name('voucher.upload_bill');



    });



});

Route::get('/payment/cancel', 'Customer\PayController@cancel')->name('cart.payment.cancel');
Route::get('/payment/alepay_success', 'Customer\PayController@alepay_success')->name('cart.payment.alepay_success');

Route::get('ref/{username}', 'Customer\AffiliatesController@ref')->name('ref');

Route::post('pay', 'Customer\PayController@store')->name('us.pay.store');
Route::get('pay-product/{product}', 'Customer\PayController@index')->name('us.pay.product');
Route::get('pay-package/{product}', 'Customer\PayController@index')->name('us.pay.package');

// Thanh toán giỏ hàng
Route::get('customer-pay', 'Customer\PayController@customer_pay')->name('w.customer_pay');
Route::post('customer-pay/store', 'Customer\PayController@store_order')->name('w.customer_pay.store');

Route::get('payment/success','Customer\PaymentController@success')->name('payment.success');
Route::get('payment/return','Customer\PaymentController@responeVnpay')->name('payment.return');

// Đăng ký thông qua giới thiệu
Route::get('/customers/{link}', 'Customer\LoginsController@register')->middleware(['checkLinkRegister']);
//Route::post('/customers/register', [LoginsController::class,'store'])->name('us.register.store');
//Đăng kí ngoài trang web
Route::get('/register', [LoginsController::class,'web_register'])->name('w.register');
Route::post('/customers/store', [LoginsController::class,'store'])->name('w.register.store');


// Thưởng tháng theo combo mua sản phẩm
Route::get('/bonus', 'Customer\OrdersController@month_bonus')->name('bonus');

// Thưởng nhóm theo ngày
Route::get('/day_bonus', 'Customer\OrdersController@day_bonus')->name('day_bonus');


//  User router (khách hàng)

 Route::group(['as' => 'w.', 'namespace' => 'Web'], function () {
    Route::get('/', 'HomewController@index')->name('index');
    /* blog */
    Route::get('/danh-sach-bai-viet', 'BlogController@blogs')->name('blogs');
    Route::get('/danh-sach-bai-viet/{category_slug}/{blog_slug}', 'BlogController@single_blog')->name('single_blog');

    /* san pham */
    Route::get('san-pham','ProductController@listProducts')->name('products');
    /* tim kiem */
    Route::get('san-pham/tim-kiem', 'ProductController@search')->name('product.search');
    Route::get('san-pham/{category}/{product}', 'ProductController@index')->name('pro.index');
    Route::get('san-pham/{slug}','ProductController@listProductsCategory')->name('products.category');


    Route::get('shop/category/{id}', 'ProductController@product_archive')->name('product.archive');
    Route::get('check-login','HomewController@check_login')->name('check_login');
    Route::get('/ve-chung-toi', 'HomewController@aboutUs')->name('about');

app/Http/Controllers/Web/CartController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Cart;
//use Gloudemans\Shoppingcart\Cart;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $total = Cart::subtotal();
        $carts = Cart::content();
        $carts_qty = Cart::content()->count();
        return view('web.cart.view')->with(compact('carts','total','carts_qty'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $product = Product::find($id);
        if(!$product) {
            session()->flash('warning','Sản phẩm không tồn tại!');
            return redirect()->back();
        }
        Cart::add($product->id,$product->name,1,$product->price,0,['image'=>$product->image]);

        return redirect()->route('w.cart.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product =Product::find($request->pro_id);
        if(!$product) {
            session()->flash('warning','Sản phẩm không tồn tại!');
            return redirect()->back();
        }
        Cart::add($product->id,$product->name,$request->qty,$product->price,0,['image'=>$product->image]);
        return redirect()->route('w.cart.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        if($request->cart) {
            foreach ($request->cart as $key=>$cart) {
                Cart::update($key, $cart);
            }
        }
        session()->flash('success','Cập nhật thành công!');
        return redirect()->route('w.cart.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($rowId)
    {
        Cart::remove($rowId);
        session()->flash('success','Xóa thành công!');
        return redirect()->route('w.cart.index');
    }
}

resources/views/web/cart/view.blade.php
@extends('web.layouts.master')
@section('page_title', 'Giỏ hàng')
@section('page_thumb', asset('hoangviet/img/vechungtoi.jpg'))
@section('content')
    <div class="container pt-5 mb-5">
        <h2 class="cart-title">Giỏ hàng</h2>
        <form id="formPay" action="{{route('w.cart.update')}}" method="post" class="mb-5 pb-5">
            @csrf
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th width="15%">Ảnh sản phẩm</th>
                        <th width="20%">Tên sản Phẩm</th>
                        <th width="15%">Giá</th>
                        <th width="10%">Số lượng</th>
{{--                        @if (customer()->check())--}}
{{--                        <th width="20%">Chiết khấu</th>--}}
{{--                        @endif--}}
                        <th width="20%">Thành tiền</th>
                        <th width="10%">Hành động</th>
                    </tr>
                </thead>
                <tbody>

                @csrf
                @foreach($carts as $cart)
                    <tr>
                        <td><img class="product-image" src="{{$cart->options->image}}" alt=""></td>
                        <td>{{$cart->name}}</td>
                        <td>{{number_format($cart->price)}} VNĐ</td>
                        <td>
                            {{-- <input class="minus is-form" type="button" value="-" > --}}
                            <input style="padding: 0" aria-label="quantity" class="input-qty" max="1000" min="1" form="formPay"  name="cart[{{$cart->rowId}}]" type="number" value="{{number_format($cart->qty)}}" >
                            {{-- <input class="plus is-form" type="button" value="+"> --}}
                        </td>
{{--                        @if (customer()->check())--}}
{{--                        <td>{{ auth('user')->user()->grant->percent }}%</td>--}}
{{--                        @endif--}}
                        <td>{{number_format($cart->price*$cart->qty)}} VNĐ</td>
                        <td>
                            <a href="{{route('w.cart.destroy',$cart->rowId)}}"  onClick="alert('Bạn có chắc chắn xóa sản phẩm khỏi giỏ hàng ?')" class="btn btn btn-sm btn-danger rounded">Xóa</a>
                        </td>
                    </tr>

                @endforeach

                <tr>
                    <td colspan="4"></td>
                    <td class="font-weight-bold">Tổng : {{$total}} VNĐ</td>
{{--                    <td class="font-weight-bold">--}}
{{--                        <input class="form-check-input" type="checkbox"> Thanh toán bằng điểm--}}
{{--                    </td>--}}
                </tr>
                </tbody>
            </table>
{{--            @if(customer()->user() && customer()->user()->point >= 10000)--}}
{{--            <p class="form-check-label d-flex justify-content-end align-center" for="pay_point">--}}
{{--                <input class="form-check-input" id="pay_point" type="checkbox" name="pay_point" style="width: auto; height: auto; opacity: 1; position: inherit; margin-right: 1rem">--}}
{{--                <span>Thanh toán bằng điểm (<span class="text-danger">{{number_format(customer()->user()->point)}} đ</span>)</span>--}}
{{--            </p>--}}
{{--            @endif--}}
            <div class="d-flex justify-content-between">
                <a class="btn btn-info" href="{{route('w.products')}}">Tiếp tục mua hàng</a>
                <div class="d-flex">
                    <button tyle="submit" class="btn btn-primary mx-2" href="">Cập nhật giỏ hàng</button>
                    <a class="btn btn-success mx-2" href="{{ route('w.customer_pay') }}">Đặt hàng</a>
                </div>
            </div>
        </form>
    </div>
@endsection
@push('css')
<style>
    .justify-content-between {
        justify-content: space-between;
    }
    .mx-2 {
        margin-left: 0.5em;
        margin-right: 0.5em;
    }
    .cart-title {
        padding-top: 20px;
        margin-bottom: 20px;
    }
    .font-weight-bold {
        font-weight: bold;
    }
    .product-image {
        width: 100%;
    }

    .buttons_added {
        opacity: 1;
        display: inline-block;
        display: -ms-inline-flexbox;
        display: inline-flex;
        white-space: nowrap;
        vertical-align: top;
    }

    .is-form {
        overflow: hidden;
        position: relative;
        background-color: #f9f9f9;
        height: 2.5rem;
        width: 2.5rem;
        padding: 0;
        text-shadow: 1px 1px 1px #fff;
        border: 1px solid #ddd;
    }

    .is-form:focus,
    .input-text:focus {
        outline: none;
    }

    .is-form.minus {
        border-radius: 4px 0 0 4px;
    }

    .is-form.plus {
        border-radius: 0 4px 4px 0;
    }

    .input-qty {
        background-color: #fff;
        height: 2.5rem;
        text-align: center;
        /*font-size: 2rem;*/
        display: inline-block;
        vertical-align: top;
        margin: 0;
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        border-left: 0;
        border-right: 0;
        padding: 0;
    }

    .input-qty::-webkit-outer-spin-button,
    .input-qty::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>
@endpush

@push('scripts')
    <script>
        $(document).ready(function(){
            $('input.input-qty').each(function() {
                var $this = $(this),
                    qty = $this.parent().find('.is-form'),
                    min = Number($this.attr('min')),
                    max = Number($this.attr('max'))
                if (min == 0) {
                    var d = 0
                } else d = min
                $(qty).on('click', function() {
                    d = Number($this.val());

                    if ($(this).hasClass('minus')) {
                        if (d > min) d += -1
                    } else if ($(this).hasClass('plus')) {
                        var x = Number($this.val()) + 1
                        if (x <= max) d +=  1
                    }
                    // console.log(d);

                    $this.attr('value', d).val(d)
                })
                $('input.input-qty').change(function(){
                    if ($(this).val() < 1 ) {
                        $(this).val(1);
                    }
                })
            })



            // $("#pay_point").change(function () {
            //     if ($('#pay_point').is(":checked"))
            //     {
            //         console.log($(this).val());
            //     }
            // })
        });
    </script>
@endpush