routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomewController;
use App\Http\Controllers\Web\AccountwController;
use App\Http\Controllers\Web\LoginwController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
// use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\LogMoneyController;
use App\Http\Controllers\Customer\LoginsController;
use App\Http\Controllers\Customer\HomesController;
use App\Http\Controllers\Customer\OrdersController;
use App\Http\Controllers\Customer\AccountController;
use App\Http\Controllers\Customer\BankAccountController;
use App\Http\Controllers\Customer\CustomersController;
use App\Http\Controllers\Customer\ProductsController;
use App\Http\Controllers\Customer\PackageController;
use App\Http\Controllers\Customer\PayController;
use App\Models\Admin;
use Illuminate\Support\Facades\Hash;

// create account admin auto

//Route::get('/create-admin', function () {
//  $data['name'] = 'admin';
//  $data['email'] = 'admin@gmail.com';
//  $data['phone'] = '0987654321';
//  $data['password'] = Hash::make('admin123');
//  Admin::create($data);
//  session()->flash('success', 'Thành công');
//  return redirect()->route('ad.admin.index');
//});

// Admin router (quản trị viên)
Route::get('admin/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('admin/login', 'Admin\LoginController@login')->name('ad.login');

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::resource('product', 'ProductController')->except('show');
    Route::post('/product/status/{id}', 'ProductController@status')->name('product.status');
    Route::get('/product/hot', 'ProductController@hot')->name('pro.hot');
    Route::get('search-product', 'ProductController@searchProduct')->name('product.searchProduct');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('customer', 'CustomerController');
    Route::get('search-customer', 'CustomerController@searchCustomer')->name('customer.searchCustomer');

    //List Khách hàng vãng lai
    Route::get('khach-hang-vang-lai','CustomerController@customer')->name('customer.customer');
    // blog
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('blog_category', 'BlogCategoryController')->except('show');

    // Cộng trừ tiền
    Route::post('/customer/money', 'CustomerController@money')->name('customer.money');
    // Route::resource('user', 'UserController');
    // Route::get('search-user', 'UserController@searchUser')->name('user.searchUser');
    Route::resource('order', 'OrderController');
    Route::get('search-order', 'OrderController@searchOrder')->name('order.searchOrder');
    Route::resource('affiliate', 'AffiliateController');
    Route::get('/log', 'LogMoneyController@index')->name('log');

    //config
    Route::resource('/config', 'ConfigController');

    //banner
    Route::resource('/banner', 'BannerController');
    Route::patch('/banner/type/{banner}', 'BannerController@type')->name('banner.type');

    Route::get('/log-bank', 'LogMoneyController@log_bank')->name('log.bank');
    Route::get('/log-wallet', 'LogMoneyController@log_wallet')->name('log.wallet');
    Route::get('/log-transaction', 'LogMoneyController@log_transaction')->name('log.transaction');
    Route::get('/log-point', 'LogMoneyController@log_point')->name('log.point');
    Route::get('/log-order', 'LogMoneyController@log_order')->name('log.order');

    // Chức năng mua điểm
    Route::get('/point', 'UserController@buy_point')->name('point.index');
    Route::post('/point/update', 'UserController@update_point')->name('point.update');

    // Quản lý nạp / rút
    Route::get('recharge','PaymentController@recharge')->name('payment.recharge');
    Route::patch('post_recharge/{id}','PaymentController@post_recharge')->name('payment.post_recharge');


    Route::get('withdraw','PaymentController@withdraw')->name('payment.withdraw');
    Route::patch('withdraw/{id}','PaymentController@post_withdraw')->name('payment.post_withdraw');
    //End

    Route::get('search-affiliate', 'AffiliateController@searchAffiliate')->name('affiliate.searchAffiliate');
    // Xuất file Excel
    Route::get('export', 'OrderController@exportOrders')->name('exportOrders');
    Route::get('export', 'OrderController@export')->name('export');

    // Quản lý danh mục sản phẩm
    Route::resource('category', 'CategoryController');

    // Tính và cộng thưởng hoa hồng theo tháng
    Route::get('/bonus',  [OrdersController::class,'month_bonus'])->name('bonus');

    // Cấu hình % hoa hồng, thu nhập, thưởng
    Route::get('rose-config', 'ConfigController@rose_config')->name('rose.config');
    Route::post('rose-update', 'ConfigController@rose_update')->name('rose.update');
    // Cấu hình thưởng nhóm theo ngày
    Route::get('group-bonus', 'ConfigController@group_bonus_config')->name('group_bonus.config');
    Route::post('group-bonus-update', 'ConfigController@group_bonus_update')->name('group_bonus.update');
    // Cấu hình thưởng thu nhập/thu nhập
    Route::get('incomes', 'ConfigController@incomes_config')->name('incomes.config');
    Route::post('incomes-update', 'ConfigController@incomes_update')->name('incomes.update');

    // Hiển thị danh sách đội nhóm
    Route::get('groups', 'AffiliateController@show_groups')->name('group.index');
    Route::get('group_detail/{group_name}', 'AffiliateController@group_detail')->name('group.group_detail');

    // Săn Voucher
    Route::get('san-voucher', 'VoucherController@index')->name('voucher.index');
    Route::post('confirm-san-voucher/{id}', 'VoucherController@confirm')->name('voucher.confirm');
    Route::post('destroy-san-voucher/{id}', 'VoucherController@destroy')->name('voucher.destroy');


});

// Customer router (Đại lý)
Route::get('customers/login', [LoginsController::class,'index'])->name('us.login.index');
Route::post('customers/login', [LoginsController::class,'login'])->name('us.login');

Route::get('customers/group', [HomesController::class,'group_money']);

Route::group(['prefix' => '/customers', 'as' => 'us.', 'namespace' => 'Customer', 'middleware' => 'customerLogin'],function () {
    Route::get('san-pham-dau','ProductsController@checkmember')->name('checkmember');
    Route::post('san-pham','ProductsController@add_to_cart')->name('product.add_to_cart');
    Route::get('san-pham-checkout','ProductsController@checkout')->name('product.checkout');
    Route::get('san-pham-reset','ProductsController@reset')->name('product.reset');
    Route::post('san-pham-thanh-toan','ProductsController@store_dau_vao')->name('product.store_dau_vao');


    Route::get('mua-san-pham-dau/{id}','ProductsController@store')->name('buycombo.store');
    Route::get('thong-tin-san-pham-dau-tu','ProductsController@info')->name('buycombo.info');
    Route::get('thanh-toan-san-pham-dau-tu','ProductController@payment')->name('buycombo.payment');
//    Route::get('mua-san-pham-dau','ProductsController@store')->name('buycombo.store');
    Route::group(['middleware' => 'checkMember'], function (){
        Route::get('/', [HomesController::class,'index'])->name('home');
        Route::resource('account', 'AccountController')->only('index','update');

        Route::get('group_detail/{group_name}', 'IonGroupController@show')->name('group.show');

        // Chuyển ví
        Route::post('bank_account', 'AccountController@bank_account')->name('bank.bank_account');
        Route::get('bank_wallet', 'AccountController@bank_wallet_view')->name('bank.bank_wallet_view');
        Route::post('bank_wallet/{user}', 'AccountController@bank_wallet')->name('bank.bank_wallet');
        Route::get('chuyen-diem', 'AccountController@bank_out_view')->name('bank.bank_out_view');
        Route::post('chuyen-diem-post', 'AccountController@bank_transfer')->name('bank.bank_out');
        Route::get('bank/search', 'AccountController@search_receiver')->name('bank.search_receiver');

        // Nạp tiền
        Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('payment-history', 'PaymentController@history')->name('payment.history');
        Route::post('payment-offline', 'PaymentController@payment_offline')->name('payment.offline');
        //End
        //Rút tiền
        //Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('rut-diem', 'PaymentController@withdraw')->name('payment.withdraw');
        Route::post('payment-withdraw', 'PaymentController@post_withdraw')->name('payment.post_withdraw');
        Route::get('lich-su-rut-diem', 'PaymentController@history_withdraw')->name('payment.history_withdraw');
        // End

        // Lịch sử giao dịch
        Route::get('/history', 'AccountController@history')->name('history');

        Route::get('order', 'OrdersController@index')->name('order.index');
        Route::resource('affiliate', 'AffiliatesController')->only('index');
        Route::resource('customer', 'CustomersController')->only('index');
        Route::resource('product', 'ProductsController')->only('index');
        Route::resource('package', 'PackageController')->only('index');
        // Route::get('pay-product/{product}', 'PayController@index')->name('pay.product')->middleware(['checkOrder']);
        Route::resource('bank', 'BankAccountController')->only('index','store','update');
        Route::get('logout', 'LoginsController@logout')->name('logout');
        Route::post('search', 'BankAccountController@search')->name('search');

        Route::get('network/affiliate', 'AffiliatesController@index')->name('aff.index');

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Customer;
use App\Models\User;
use App\Models\Role;
use App\Models\IonGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $customers = User::orderBy('id', 'DESC')->paginate(10);
        foreach ($customers as $key => $customer) {
            $groups = IonGroup::where('leader_id', $customer->id)->select('leader_id')
            ->selectRaw('COUNT(*) as members')
            ->groupBy(['leader_id', 'group_name'])
            ->get()->count();
            // dd($groups);
            $customer['groups'] = $groups;
        }
        return view('admin.customers.index', compact('customers'));
    }

    public function create()
    {
        return view('admin.customers.create');
    }

    public function store(CreateUserRequest $request)
    {
        // tạo cộng tác viên mới, tạo bởi admin master
        $data = $request->only('name', 'email', 'phone', 'gender', 'address','username');
        $data['type'] = 2;
        $data['url'] = time();
        $data['level'] = 1;
        $data['password'] = Hash::make($request->password);
        $customer = User::create($data);

        // tạo parent của cộng tác viên mới
        $role['user_id'] = $customer->id;
        $role['parent_id'] = 0;
        Role::create($role);

        session()->flash('success', 'Thêm tài khoản cộng tác viên thành công');
        return redirect()->route('ad.customer.index');
    }


    public function edit(User $customer)
    {
        return view('admin.customers.edit', compact('customer'));
    }

    public function update(UpdateUserRequest $request, User $customer)
    {
        $data = $request->all();
        $data['password'] = Hash::make($request->password);

        if ($request->password) {
            $request->validate([
                'password' => 'required|min:6|max:15'
            ]);
            $data['password'] = Hash::make($request->password);
        }

        $customer->update($data);
        session()->flash('success', 'Thành công');

        return redirect()->route('ad.customer.index');
    }

    public function searchCustomer(Request $request) {
        // if($request->data==''){
        //     session()->flash('error', 'Bạn chưa nhập username hoặc SĐT cần tìm');
        //     return redirect()->route('ad.customer.index');
        // }
        if($request->find_option == 'username'){
            $customers = User::when($request->data, function ($query) use ($request) {
                return $query->where('username', $request->data);
            })
            ->when($request->rate, function ($query) use ($request) {
                return $query->where('rate', $request->rate);
            })
            ->paginate(20);
        }
        if($request->find_option == 'phone'){
            $customers = User::when($request->data, function ($query) use ($request) {
                return $query->where('phone', $request->data);
            })
            ->when($request->rate, function ($query) use ($request) {
                return $query->where('rate', $request->rate);
            })
            ->paginate(20);
        }
        if($customers->count()==0){
            session()->flash('error', 'Không tồn tại người dùng thỏa mãn');
            return redirect()->route('ad.customer.index');
        }
        // $customers = User::Where('name', 'like', '%' .$request->name. '%')->Where('type',1)->orderBy('id', 'DESC')->paginate(20);
        return view('admin.customers.index', compact('customers'));
    }

    public function money(Request $request){
        $customer = User::where('id',$request->user_id)->first();
        switch ($request->type) {
            case 0:
                $customer->wallet1 += $request->money;
                $plus = $customer->update();
                if($plus){
                    session()->flash('success', 'Thành công');
                    return redirect()->back();
                } else {
                    session()->flash('error', 'Thất bại');
                    return redirect()->back();
                }
                break;
            case 1:
                $customer->wallet1 -= $request->money;
                $plus = $customer->update();
                if($plus){
                    session()->flash('success', 'Thành công');
                    return redirect()->back();
                }else {
                    session()->flash('error', 'Thất bại');
                    return redirect()->back();
                }
                break;
            case 2:
                $money = new User();
                $group_money = $money->group_money($customer);      // Doanh thu của thành viên
                $customer->wallet1 += $group_money*1/100;           // Cộng hoa hồng bằng 1% tổng doanh thu hàng tháng
                $plus = $customer->update();
                if($plus){
                    session()->flash('success', 'Thành công');
                    return redirect()->back();
                }else {
                    session()->flash('error', 'Thất bại');
                    return redirect()->back();
                }
                break;
            default:
                // do something if none of the above cases match
        }
        if($request->type==0){
            // Cộng tiền
            $customer->wallet1 += $request->money;
            $plus = $customer->update();
            if($plus){
                session()->flash('success', 'Thành công');
                return redirect()->back();
            } else {
                session()->flash('error', 'Thất bại');
                return redirect()->back();
            }
        } else {
            $customer->wallet1 -= $request->money;
            $plus = $customer->update();
            if($plus){
                session()->flash('success', 'Thành công');
                return redirect()->back();
            }else {
                session()->flash('error', 'Thất bại');
                return redirect()->back();
            }
        }

    }

    public  function customer() {
        $customers = Customer::orderBy('id','DESC')->paginate(20);
        return view('admin.users.kh-vang-lai', compact('customers'));
    }
}

app/Http/Controllers/Customer/HomesController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Models\LogMoney;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Order;


class HomesController extends Controller
{
    public function index(Request $request)
    {
        $customer = Auth('user')->user();
        if($customer->affiliate->count()){
            foreach ($customer->affiliate as $affiliate) {
                $order_id[] = $affiliate->order_id;
            }
            $totalOrder = Order::whereIn('id', $order_id)->get()->sum('total_money');
        }else{
            $totalOrder = 0;
        }
        session(['totalMoneyAffiliate' => $customer->affiliate ? $customer->affiliate->sum('money') : 0]);
        ($customer->role) ? $parent = $customer->role->parent : $parent = 0;
        $money = new User();
        $group_money = $money->group_money($customer);
        $childs = User::where('f1_id', $customer->id)->get();

        // Hoa hồng trực tiếp đã nhận
        $hhtt = LogMoney::where('user_id', $customer->id)->where('type',1)->where('status',1)->sum('money');

        // Hoa hồng quản lý đã nhận
        $hhql = LogMoney::where('user_id', $customer->id)->where('type',2)->where('status',1)->sum('money');

        return view('customer.home',compact('customer','parent','totalOrder', 'group_money', 'childs', 'hhtt', 'hhql'));
    }


}

resources/views/customer/account.blade.php
@extends('customer.layouts.master')
@section('page_title', 'Tài khoản')
@section('page_id', 'page-account')
@section('content')
<section class="content-wrapper bg-background-main" style="min-height: 682.8px;">
  <!-- Main content -->
  <section class="content" style="padding:0px;">
    <div class="container-fluid" style="padding-top:10px; margin-bottom: 50px; padding: 10px !important;">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h4 class="card-title ">
                <i class="fa fa-user-circle"></i> Thông tin cá nhân
              </h4>
            </div>
            <div class="card-body">
              <div class="ribbon-wrapper ribbon-lg">
                <div class="ribbon bg-success">Hoàng Kim Mart</div>
              </div>
              <form action="{{route('us.account.update',$customer)}}" method="post" >
                @method('PUT')
                @csrf
                <div class="col-md-12">
                  <h5>THÔNG TIN QUẢN LÝ</h5>
                  <div class="form-group">
                    <label>Đại lý cấp trên</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-user"></i>
                        </span>
                      </div>
                      <input type="text" value="{{(customer()->user()->f1_id()) ? customer()->user()->f1_id()->username : ''}}" readonly="readonly"  class="form-control">
                    </div>
                  </div>

                  <h5>THÔNG TIN CÁ NHÂN</h5>
                  <div class="form-group">
                    <label>Tên truy cập</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-user"></i>
                        </span>
                      </div>
                      <input type="text" name="username" value="{{ $customer->username }}" readonly=""  class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Họ và tên (*)</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-user"></i>
                        </span>
                      </div>
                      <input name="name" type="text" value="{{ $customer->name }}"  class="form-control">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Giới tính (*)</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-venus-mars"></i>
                        </span>
                      </div>
                      <select name="gender"  class="form-control">
                        <option value="1" {{$customer->gender == 1 ? 'selected' : ''}}>Nam</option>
                        <option value="0" {{$customer->gender == 0 ? 'selected' : ''}}>Nữ</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Điện thoại (*)</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-phone"></i>
                        </span>
                      </div>
                      <input name="phone" type="text" value="{{ $customer->phone }}" maxlength="10" class="form-control numbers10" required="" placeholder="Phone" autocomplete="off">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Email</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-envelope"></i>
                        </span>
                      </div>
                      <input name="email" type="text" value="{{ $customer->email }}" maxlength="50"  class="form-control" placeholder="Nếu có">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Địa chỉ</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-envelope"></i>
                        </span>
                      </div>
                      <input name="address" type="text" value="{{ $customer->address }}" maxlength="50"  class="form-control" placeholder="Chưa cập nhật">
                    </div>
                  </div>
                  {{-- <h5>THÔNG TIN NGÂN HÀNG</h5>
                  <div class="form-group">
                    <label>Ngân hàng</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-university"></i>
                        </span>
                      </div>
                      <select name="bank"  class="form-control">
                        <option value="">-- Chọn ngân hàng --</option>
                        <option value="{{ $customer->bankAccount ?  $customer->bankAccount->bank : '' }}" selected></option>
                        <option value="ACB">ACB</option>
                        <option value="AGRIBANK">AGRIBANK</option>
                        <option value="BIDV">BIDV</option>
                        <option value="DONGA BANK">DONGA BANK</option>
                        <option value="EXIMBANK">EXIMBANK</option>
                        <option value="HDBANK">HDBANK</option>
                        <option value="MB BANK">MB BANK</option>
                        <option value="MSB">MSB</option>
                        <option value="NAM A BANK">NAM A BANK</option>
                        <option value="OCB">OCB</option>
                        <option value="SACOMBANK">SACOMBANK</option>
                        <option value="SCB">SCB</option>
                        <option value="SHB">SHB</option>
                        <option value="SHINHANBANK">SHINHANBANK</option>
                        <option value="TECHCOMBANK">TECHCOMBANK</option>
                        <option value="TPBank">TPBank</option>
                        <option value="VIB">VIB</option>
                        <option value="VIETABANK">VIETABANK</option>
                        <option value="VIETCOMBANK">VIETCOMBANK</option>
                        <option value="VIETINBANK">VIETINBANK</option>
                        <option value="VPBank">VPBank</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Số tài khoản</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-money-check-alt"></i>
                        </span>
                      </div>
                      <input name="number" type="text" maxlength="20"  class="form-control" placeholder="Số tài khoản" autocomplete="off" value="{{ $customer->bankAccount ? $customer->bank->number : '' }}">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Chủ tài khoản</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-user"></i>
                        </span>
                      </div>
                      <input name="name1" type="text" value="{{ $customer->bankAccount ? $customer->bank->name : '' }}" maxlength="30"  class="form-control" placeholder="Tên chủ tài khoản">
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Chi nhánh</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="fas fa-map-marker"></i>
                        </span>
                      </div>
                      <input name="branch" type="text" value="{{ $customer->bankAccount ? $customer->bank->branch : '' }}" maxlength="30"  class="form-control" placeholder="Chi nhánh nếu có" autocomplete="off">
                    </div>
                  </div> --}}
                  <center>
                    <button type="submit" value="submit" class="btn-submit-form btn  bg-background" style="width:200px;color:white; font-weight:bold;">CẬP NHẬT</button>
                  </center>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</section>
<script>
  $(".btn-submit-form").click(function(){
    console.log(1);
  });
</script>
@endsection

resources/views/customer/history.blade.php
@extends('customer.layouts.master')

@section('page_title', 'Lịch sử giao dịch')

@section('page_id', 'page-order')

@section('content')
<section class="content-wrapper bg-background-main" style="min-height: 682.8px;">
  <!-- Main content -->
  <section class="content" style="padding:0px;">
    <div class="container-fluid" style="padding-top:10px; margin-bottom: 50px; padding: 10px !important;">
      <h4 class="mb-2">Lịch sử giao dịch</h4>
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12"></div>
                <input type="hidden" name="ctl27$txtQuantity" id="ctl27_txtQuantity">
                {{-- <div class="col-md-12"> Đơn hàng của bạn </div> --}}
                <div style="min-width:100%;overflow-x:auto;">
                  <table id="thistory" class="table table-bordered table-striped bg-white table-hover" style="font-size:15px; min-width:1000px">
                    <thead>
                      <tr>
                        <th style="min-width:120px;">STT</th>
                        <th style="min-width:120px;">Số điểm trước thay đổi</th>
                        <th style="min-width:120px;">Số điểm thay đổi</th>
                        <th style="min-width:120px;">Số điểm sau thay đổi</th>
                        <th style="min-width:120px;">Lí do</th>
                        <th style="min-width:120px;">Thời gian</th>
                      </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1;
                        @endphp
                      @foreach ($histories as $item)
                          <tr>
                              <td>{{ $i }}</td>
                              <td>{{ number_format( $item->before, 0, ',','.')}}đ</td>
                              @if ($item->status)
                              <td class="bold text-success">+{{ number_format( $item->money, 0, ',','.')}}đ</td>
                              @else
                              <td class="bold text-danger">-{{ number_format( $item->money, 0, ',','.')}}đ</td>
                              @endif
                              <td>{{ number_format( $item->after, 0, ',','.')}}đ</td>
                              <td>{{ $item->reason}}</td>
                              <td>{{ \Carbon\Carbon::createFromDate($item->created_at)->format('H:i:s d/m/Y') }}</td>
                          </tr>
                          @php
                            $i++;
                          @endphp
                      @endforeach
                      @if ($histories->count()==0)
                      <tr>
                        <td class="text-center" colspan="10">Chưa có dữ liệu để hiển thị</td>
                      </tr>
                      @endif
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal" id="mdOrder" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 99999999">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content" style="width:100%;">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel"> Thông tin đơn hàng </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-md-12 mb-2" style="line-height:40px;" id="orderInfo"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <style type="text/css">
        .dfl {
          display: flex;
          justify-content: space-between;
        }
      </style>
      <script src="/Scripts/pachis.js?v=0.1"></script>
    </div>
  </section>
</section>
@endsection