routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomewController;
use App\Http\Controllers\Web\AccountwController;
use App\Http\Controllers\Web\LoginwController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProductController;
// use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\LogMoneyController;
use App\Http\Controllers\Customer\LoginsController;
use App\Http\Controllers\Customer\HomesController;
use App\Http\Controllers\Customer\OrdersController;
use App\Http\Controllers\Customer\AccountController;
use App\Http\Controllers\Customer\BankAccountController;
use App\Http\Controllers\Customer\CustomersController;
use App\Http\Controllers\Customer\ProductsController;
use App\Http\Controllers\Customer\PackageController;
use App\Http\Controllers\Customer\PayController;
use App\Models\Admin;
use Illuminate\Support\Facades\Hash;

// create account admin auto

//Route::get('/create-admin', function () {
//  $data['name'] = 'admin';
//  $data['email'] = 'admin@gmail.com';
//  $data['phone'] = '0987654321';
//  $data['password'] = Hash::make('admin123');
//  Admin::create($data);
//  session()->flash('success', 'Thành công');
//  return redirect()->route('ad.admin.index');
//});

// Admin router (quản trị viên)
Route::get('admin/login', 'Admin\LoginController@index')->name('ad.login.index');
Route::post('admin/login', 'Admin\LoginController@login')->name('ad.login');

Route::group(['prefix' => '/admin', 'as' => 'ad.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('index');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::resource('product', 'ProductController')->except('show');
    Route::post('/product/status/{id}', 'ProductController@status')->name('product.status');
    Route::get('/product/hot', 'ProductController@hot')->name('pro.hot');
    Route::get('search-product', 'ProductController@searchProduct')->name('product.searchProduct');
    Route::resource('admin', 'AdminController')->except('show');
    Route::resource('customer', 'CustomerController');
    Route::get('search-customer', 'CustomerController@searchCustomer')->name('customer.searchCustomer');

    //List Khách hàng vãng lai
    Route::get('khach-hang-vang-lai','CustomerController@customer')->name('customer.customer');
    // blog
    Route::resource('blog', 'BlogController')->except('show');
    Route::resource('blog_category', 'BlogCategoryController')->except('show');

    // Cộng trừ tiền
    Route::post('/customer/money', 'CustomerController@money')->name('customer.money');
    // Route::resource('user', 'UserController');
    // Route::get('search-user', 'UserController@searchUser')->name('user.searchUser');
    Route::resource('order', 'OrderController');
    Route::get('search-order', 'OrderController@searchOrder')->name('order.searchOrder');
    Route::resource('affiliate', 'AffiliateController');
    Route::get('/log', 'LogMoneyController@index')->name('log');

    //config
    Route::resource('/config', 'ConfigController');

    //banner
    Route::resource('/banner', 'BannerController');
    Route::patch('/banner/type/{banner}', 'BannerController@type')->name('banner.type');

    Route::get('/log-bank', 'LogMoneyController@log_bank')->name('log.bank');
    Route::get('/log-wallet', 'LogMoneyController@log_wallet')->name('log.wallet');
    Route::get('/log-transaction', 'LogMoneyController@log_transaction')->name('log.transaction');
    Route::get('/log-point', 'LogMoneyController@log_point')->name('log.point');
    Route::get('/log-order', 'LogMoneyController@log_order')->name('log.order');

    // Chức năng mua điểm
    Route::get('/point', 'UserController@buy_point')->name('point.index');
    Route::post('/point/update', 'UserController@update_point')->name('point.update');

    // Quản lý nạp / rút
    Route::get('recharge','PaymentController@recharge')->name('payment.recharge');
    Route::patch('post_recharge/{id}','PaymentController@post_recharge')->name('payment.post_recharge');


    Route::get('withdraw','PaymentController@withdraw')->name('payment.withdraw');
    Route::patch('withdraw/{id}','PaymentController@post_withdraw')->name('payment.post_withdraw');
    //End

    Route::get('search-affiliate', 'AffiliateController@searchAffiliate')->name('affiliate.searchAffiliate');
    // Xuất file Excel
    Route::get('export', 'OrderController@exportOrders')->name('exportOrders');
    Route::get('export', 'OrderController@export')->name('export');

    // Quản lý danh mục sản phẩm
    Route::resource('category', 'CategoryController');

    // Tính và cộng thưởng hoa hồng theo tháng
    Route::get('/bonus',  [OrdersController::class,'month_bonus'])->name('bonus');

    // Cấu hình % hoa hồng, thu nhập, thưởng
    Route::get('rose-config', 'ConfigController@rose_config')->name('rose.config');
    Route::post('rose-update', 'ConfigController@rose_update')->name('rose.update');
    // Cấu hình thưởng nhóm theo ngày
    Route::get('group-bonus', 'ConfigController@group_bonus_config')->name('group_bonus.config');
    Route::post('group-bonus-update', 'ConfigController@group_bonus_update')->name('group_bonus.update');
    // Cấu hình thưởng thu nhập/thu nhập
    Route::get('incomes', 'ConfigController@incomes_config')->name('incomes.config');
    Route::post('incomes-update', 'ConfigController@incomes_update')->name('incomes.update');

    // Hiển thị danh sách đội nhóm
    Route::get('groups', 'AffiliateController@show_groups')->name('group.index');
    Route::get('group_detail/{group_name}', 'AffiliateController@group_detail')->name('group.group_detail');

    // Săn Voucher
    Route::get('san-voucher', 'VoucherController@index')->name('voucher.index');
    Route::post('confirm-san-voucher/{id}', 'VoucherController@confirm')->name('voucher.confirm');
    Route::post('destroy-san-voucher/{id}', 'VoucherController@destroy')->name('voucher.destroy');


});

// Customer router (Đại lý)
Route::get('customers/login', [LoginsController::class,'index'])->name('us.login.index');
Route::post('customers/login', [LoginsController::class,'login'])->name('us.login');

Route::get('customers/group', [HomesController::class,'group_money']);

Route::group(['prefix' => '/customers', 'as' => 'us.', 'namespace' => 'Customer', 'middleware' => 'customerLogin'],function () {
    Route::get('san-pham-dau','ProductsController@checkmember')->name('checkmember');
    Route::post('san-pham','ProductsController@add_to_cart')->name('product.add_to_cart');
    Route::get('san-pham-checkout','ProductsController@checkout')->name('product.checkout');
    Route::get('san-pham-reset','ProductsController@reset')->name('product.reset');
    Route::post('san-pham-thanh-toan','ProductsController@store_dau_vao')->name('product.store_dau_vao');


    Route::get('mua-san-pham-dau/{id}','ProductsController@store')->name('buycombo.store');
    Route::get('thong-tin-san-pham-dau-tu','ProductsController@info')->name('buycombo.info');
    Route::get('thanh-toan-san-pham-dau-tu','ProductController@payment')->name('buycombo.payment');
//    Route::get('mua-san-pham-dau','ProductsController@store')->name('buycombo.store');
    Route::group(['middleware' => 'checkMember'], function (){
        Route::get('/', [HomesController::class,'index'])->name('home');
        Route::resource('account', 'AccountController')->only('index','update');

        Route::get('group_detail/{group_name}', 'IonGroupController@show')->name('group.show');

        // Chuyển ví
        Route::post('bank_account', 'AccountController@bank_account')->name('bank.bank_account');
        Route::get('bank_wallet', 'AccountController@bank_wallet_view')->name('bank.bank_wallet_view');
        Route::post('bank_wallet/{user}', 'AccountController@bank_wallet')->name('bank.bank_wallet');
        Route::get('chuyen-diem', 'AccountController@bank_out_view')->name('bank.bank_out_view');
        Route::post('chuyen-diem-post', 'AccountController@bank_transfer')->name('bank.bank_out');
        Route::get('bank/search', 'AccountController@search_receiver')->name('bank.search_receiver');

        // Nạp tiền
        Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('payment-history', 'PaymentController@history')->name('payment.history');
        Route::post('payment-offline', 'PaymentController@payment_offline')->name('payment.offline');
        //End
        //Rút tiền
        //Route::get('payment', 'PaymentController@index')->name('payment.index');
        Route::get('rut-diem', 'PaymentController@withdraw')->name('payment.withdraw');
        Route::post('payment-withdraw', 'PaymentController@post_withdraw')->name('payment.post_withdraw');
        Route::get('lich-su-rut-diem', 'PaymentController@history_withdraw')->name('payment.history_withdraw');
        // End

        // Lịch sử giao dịch
        Route::get('/history', 'AccountController@history')->name('history');

        Route::get('order', 'OrdersController@index')->name('order.index');
        Route::resource('affiliate', 'AffiliatesController')->only('index');
        Route::resource('customer', 'CustomersController')->only('index');
        Route::resource('product', 'ProductsController')->only('index');
        Route::resource('package', 'PackageController')->only('index');
        // Route::get('pay-product/{product}', 'PayController@index')->name('pay.product')->middleware(['checkOrder']);
        Route::resource('bank', 'BankAccountController')->only('index','store','update');
        Route::get('logout', 'LoginsController@logout')->name('logout');
        Route::post('search', 'BankAccountController@search')->name('search');

        Route::get('network/affiliate', 'AffiliatesController@index')->name('aff.index');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Product;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_name', 'slug', 'description'
    ];
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.product-categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product-categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $save = $request->only('category_name', 'description');
        $save['slug'] = Str::slug($request->category_name);
        Category::create($save);
        if($save){
            session()->flash('success', 'Thao tác thành công');
            return redirect()->route('ad.category.index');
        } else {
            session()->flash('error', 'Thao tác thất bại');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.product-categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $update = $request->only('category_name', 'description');
        $update['slug'] = Str::slug($request->category_name);
        $category->update($update);
        if($update){
            session()->flash('success', 'Thao tác thành công');
            return redirect()->route('ad.category.index');
        } else {
            session()->flash('error', 'Thao tác thất bại');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash('success', 'Xóa thành công');
        return redirect()->route('ad.category.index');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Thêm mới danh mục bài viết')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.blog_category.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.blog_category.store') }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên danh mục<span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên bài viết&quot;" value="{{ old('name') }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="description">Mô tả</label>
                                    <textarea  type="text" id="description" class="form-control" name="description">{{ old('description') }}</textarea>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="image">Hình ảnh<span class="required">*</span></label>
                                    <div>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-new thumbnail" style="width: 200px;">
                                                <img class="img-responsive" src="{{ asset('images/no_image.png') }}" alt="" />
                                            </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail" style="height: 200px"></div>
                                            <div>
                                                <span class="btn default btn-file">
                                                    <span class="fileinput-new">Chọn ảnh</span>
                                                    <span class="fileinput-exists">Đổi ảnh</span>
                                                    <input type="file" accept="image/*" name="image">
                                                </span>
                                                <a href="javascript:void(0);" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Xóa</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Tạo mới</button>
                            <a href="{{ route('ad.blog_category.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
@endpush

@prepend('scripts')
<script src="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@include('admin.lib.tinymce-setup')

@endprepend

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Chỉnh sửa danh mục bài viết')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.blog_category.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.blog_category.update', $blog_category) }}" method="POST" @submit.prevent="onSubmit" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group" :class="[errors.has('name') ? 'has-error' : '']">
                                    <label for="name">Tên danh mục<span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" v-validate="'required'" data-vv-as="&quot;Tên danh mục&quot;" value="{{ $blog_category->name }}">
                                    <span class="help-block" v-if="errors.has('name')">@{{ errors.first('name') }}</span>
                                </div>
                                <div class="form-group">
                                    <label for="description">Mô tả</label>
                                    <textarea  type="text" id="description" class="form-control" name="description">{{ $blog_category->description }}</textarea>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="image">Hình ảnh<span class="required">*</span></label>
                                    <div>
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <div class="fileinput-new thumbnail" style="width: 200px;">
                                                <img class="img-responsive" src="{{ $blog_category->image }}" alt="" />
                                            </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail" style="height: 200px"></div>
                                            <div>
                                                <span class="btn default btn-file">
                                                    <span class="fileinput-new">Chọn ảnh</span>
                                                    <span class="fileinput-exists">Đổi ảnh</span>
                                                    <input type="file" accept="image/*" name="image">
                                                </span>
                                                <a href="javascript:void(0);" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Xóa</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Cập nhật</button>
                            <a href="{{ route('ad.blog_category.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
<link href="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" rel="stylesheet" type="text/css" />
@endpush

@prepend('scripts')
<script src="{{ asset('global/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
@include('admin.lib.tinymce-setup')

@endprepend

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('page_title', 'Danh sách chuyên mục bài viết')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('ad.blog_category.create')}}" class="btn btn-circle btn-sm btn-primary"> <i class="fa fa-plus"></i> Thêm mới</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title=""></a>
                    </div>
                </div>
                <div class="portlet-title">
                    <form action="" method="GET">
                        <div class="row">
                            <div class="col-md-10">
                                <div class="form-group">
                                    <input type="text" placeholder="Nhập tên bài viết cần tìm..." name="name" class="form-control" value="{{ old('name') }}" id="name" >
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <button class="btn btn-primary form-control" type="submit">Tìm kiếm</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="portlet-body" style="background: #fff">
                    <table class="table table-striped table-bordered table-hover" id="admin-table">
                        <thead>
                        <tr>
                            <th width="3%">ID</th>
                            <th width="9%">Ảnh</th>
                            <th>Tên chuyên mục</th>
                            <th>Mô tả</th>
                            <th width="9%">Slug</th>
                            <th width="110">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($categories as $key => $blog_category)
                            <tr>
                                <td>{{ $blog_category->id }}</td>
                                <td><img src="{{$blog_category->image}}" style="max-width: 25px" alt=""></td>
                                <td>{{ $blog_category->name }}</td>
                                <td>{{ $blog_category->description }}</td>
                                <td>{{ $blog_category->slug }}</td>
                                <td>
                                    <a class="btn btn-circle btn-sm btn-warning" href="{{ route('ad.blog_category.edit', $blog_category) }}"><i class="fa fa-pencil"></i></a>
                                    <form action="{{ route('ad.blog_category.destroy', $blog_category) }}" id="delete-course-item-form" style="display: inline-block" method="POST" onsubmit="return confirm('Bạn có chắc chắn muốn xóa?');">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-circle btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{-- <div class="text-center">
                        {{ $categorys->links('web.layouts.paginate') }}
                    </div> --}}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <!-- END PAGE LEVEL PLUGINS -->
@endpush

@push('scripts')
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    {{-- <script src="{{ asset('global/plugins/select2/js/select2.min.js') }}" type="text/javascript"></script> --}}
    <!-- END PAGE LEVEL SCRIPTS -->
@endpush